### ISSUE TITLE
nosetests failed

### ISSUE THREAD

**Issue by auvilink** [nineties/py-videocore#49]
======================================================================
ERROR: test_raw.test_raw_hex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pi/vision/py-videocore/tests/test_raw.py", line 16, in test_raw_hex
    print_qhex(raw_hex, file = f)
  File "/home/pi/vision/py-videocore/videocore/assembler.py", line 923, in print_qhex
    print("0x{3:02X}{2:02X}{1:02X}{0:02X}, 0x{7:02X}{6:02X}{5:02X}{4:02X},".format(*c), file = file)
TypeError: unicode argument expected, got 'str'

----------------------------------------------------------------------

**Comment by LoekHabets** [comment]
I've had the same error but everything else seems fine. At that point nearly all tests have basically been passed, but there is a compiler error in de nosetests code. You shouldn't really worry about this. The hello_world.py also allows you to test stability in a way, by checking if the errors aren't too big (usually less than 1e-4). You can also compare the absolute error in sgemm.py with the error visible in the picture from the readme file.
